casado(juan,ana).
padre(juan,julio).
padre(juan,elena).
padre(juan,fernando).
casado(julio,maria).
casado(elena,javier).
padre(julio,isabel).
padre(julio,gonzalo).
padre(julio,alvaro).
padre(elena,beatriz).
padre(elena,eva).
padre(elena,guillermo).

padre(X,Z):-casado(Y,X),padre(Y,Z).
hijo(X,Y):-padre(Y,X).
abuelo(X,Z):-padre(X,Y),padre(Y,Z).
abuelo(X,Z):-casado(Y,X),abuelo(Y,Z).
hermano(X,Z):-padre(Y,X),padre(Y,Z).
tio(X,Y):-padre(Z,Y),hermano(X,Z).
primo(X,Y):-tio(Z,X),padre(Z,Y).
sobrino(X,Y):-tio(Y,X).
